// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/volume-designs/CleanPro.tsx": () => import("../components/mockups/volume-designs/CleanPro.tsx"),
  "./components/mockups/volume-designs/FieldTool.tsx": () => import("../components/mockups/volume-designs/FieldTool.tsx"),
  "./components/mockups/volume-designs/PrecisionTool.tsx": () => import("../components/mockups/volume-designs/PrecisionTool.tsx")
};
